# Generated by Django 5.2.8 on 2025-11-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantName', models.CharField(max_length=100)),
                ('plantPrice', models.IntegerField()),
                ('plantBenefits', models.CharField(max_length=300)),
                ('plantType', models.CharField(choices=[('Fruit', 'Fruit'), ('Veg', 'Veg')], max_length=100)),
            ],
        ),
    ]
